services:
  spark-master:
    image: bitnami/spark:3.5.2
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    env_file:
      - master.env
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.5.2
    container_name: spark-worker
    env_file:
      - worker.env
    depends_on:
      - spark-master
    networks:
      - spark-network
  fastapi:
    build:
      context: ../../
      dockerfile: ./docker/fastapi/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ../../app:/app  # Mount the local app directory to the container
      - ../../requirements.txt:/tmp/requirements.txt
    networks:
      - spark-network



networks:
  spark-network:
    driver: bridge